name: tests

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - staging
  schedule:
    - cron: 0 0 * * *
jobs:
  amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.2"
          gleam-version: "1.6.3"
      - uses: actions/setup-node@v4
        with:
          node-version: "22.13.1"
      - name: Download dependencies
        run: gleam deps download
      - name: Update dependencies
        run: gleam update
      - name: Run tests (Erlang)
        run: gleam test --target erlang
      - name: Run tests (JavaScript/Node.js)
        run: gleam test --target javascript --runtime node
  s390x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup alpine:3.21 for s390x
        uses: jirutka/setup-alpine@v1
        with:
          arch: s390x
          branch: v3.21
          packages: >
            gleam=1.6.3-r0
            nodejs=22.13.1-r0
      - name: Download dependencies
        run: gleam deps download
        shell: alpine.sh {0}
      - name: Update dependencies
        run: gleam update
        shell: alpine.sh {0}
      - name: Run tests (Erlang)
        run: gleam test --target erlang
        shell: alpine.sh {0}
      - name: Run tests (JavaScript/Node.js)
        run: gleam test --target javascript --runtime node
        shell: alpine.sh {0}