name: tests

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - staging
env:
  GLEAM_VERSION: "1.9.1"
jobs:
  amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.2"
          gleam-version: "${{ env.GLEAM_VERSION }}"
      - uses: actions/setup-node@v4
        with:
          node-version: "22.13.1"
      - name: Download dependencies
        run: gleam deps download
      - name: Update dependencies
        run: gleam update
      - name: Run tests (Erlang)
        run: gleam test --target erlang
      - name: Run tests (JavaScript/Node.js)
        run: gleam test --target javascript --runtime node
  s390x:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup alpine:3.21 for s390x
        uses: jirutka/setup-alpine@v1
        with:
          arch: s390x
          branch: edge
          packages: >
            cargo
            curl
            erlang-dev
            make
            nodejs
            tar
      - name: Build Gleam
        run: |
          curl -LO "https://github.com/gleam-lang/gleam/archive/refs/tags/v${{ env.GLEAM_VERSION }}.tar.gz"
          tar -xvzf "v${{ env.GLEAM_VERSION }}.tar.gz"
          cd "./gleam-${{ env.GLEAM_VERSION }}"
          make build
          make install
        shell: alpine.sh --root {0}
      - name: Download dependencies
        run: gleam deps download
        shell: alpine.sh {0}
      - name: Update dependencies
        run: gleam update
        shell: alpine.sh {0}
      - name: Run tests (Erlang)
        run: gleam test --target erlang
        shell: alpine.sh {0}
      - name: Run tests (JavaScript/Node.js)
        run: gleam test --target javascript --runtime node
        shell: alpine.sh {0}