name: tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
      - staging
  schedule:
    - cron: 00 10 * * *
env:
  GLEAM_VERSION: "1.11.0"
  OTP_VERSION: "27.3"
  NODEJS_VERSION: "22.13.1"
jobs:
  amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "${{ env.OTP_VERSION }}"
          gleam-version: "${{ env.GLEAM_VERSION }}"
      - uses: actions/setup-node@v4
        with:
          node-version: "${{ env.NODEJS_VERSION }}"
      - name: Download dependencies
        run: gleam deps download
      - name: Update dependencies
        run: gleam update
      - name: Run tests (Erlang)
        run: gleam test --target erlang
      - name: Run tests (JavaScript/Node.js)
        run: gleam test --target javascript --runtime node